# Generated by Django 3.0.7 on 2020-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptName', models.CharField(max_length=100)),
                ('ptIdCard', models.IntegerField()),
                ('ptPrice', models.FloatField()),
                ('ptPhone', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
